---
title: "Amberson Towers Condominum" # only for pdf output
subtitle: "Amberson Towers Code of Regulations" # only for html output
author: "Draft by Governance Committee"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

***


## ARTICLE I: Applicable Statute {-}

This Code of Regulations is adopted pursuant to the Unit Property Act of the Commonwealth of Pennsylvania, (Act of July 3, 1963, P.L. 196, 68P.S. Sec. 700.301) 

## ARTICLE II: Identity of Property  {-}

The property to which this Code shall apply is described in the Declaration recorded in the Recorder's Office of Allegheny County, Pennsylvania, in Deed Book Volume 5909 , Page 507 , and in the Declaration Plan recorded in said office in Plan Book Volume 103, Pages 167 to 193 on February 15, 1978. 

## ARTICLE III: Name and Address {-}

### Section 1 {-}

The condominium shall be known by the name of AMBERSON TOWERS. 

### Section 2 {-}

The registered office of Amberson Towers shall be 5 Bayard Road, Pittsburgh, Pennsylvania 15213.

## ARTICLE IV: Meetings and Voting Rights of Unit Owner {-}

### Section 1 {-}

All meetings of Unit Owners shall be held at the principal office of Amberson Towers or at such other place within the County of Allegheny, Pennsylvania, as the Council shall determine from time to time. 

### Section 2 {-}

Beginning with the year 1979, the annual meeting of the Unit Owners shall be held on the third Monday of May in each year at 8:00 o'clock p.m., if not a legal holiday, and if a legal holiday, then on the next secular day following at the same hour. At such meetings, the Unit Owners shall elect the Council and transact such other business as may come before the meeting. 

### Section 3 {-}

Special meetings of the Unit Owners may be called at any time after the annual meeting of the Unit Owners in 1979, for any purpose or purposes by the President, or by a majority of the Council or by not less than twenty percent (20%) of all of the then Unit Owners entitled to vote at the meeting called. At any time upon written request of any person or persons entitled to call a special meeting, it shall be the duty of the Secretary to call the meeting of the Unit Owners entitled to vote thereat, but no less than ten (10) nor more than fifteen (15) days after the receipt of the request. If the Secretary shall neglect or refuse to issue such call, the person or persons making the request may do so. All requests for special meetings shall be in writing and shall specify the purpose or purposes thereof. The business to be transacted at all special meetings shall be limited to the purpose or purposes set forth in the notice thereof and matters germane thereto. 

### Section 4 {-}

Written notice of each meeting of the Unit Owners shall be given by or at the direction of the Secretary or other person authorized to call the meeting, by mailing a copy of such notice, postage prepaid, at least ten (10) days before such meeting to each Unit Owner entitled to vote thereat, addressed to the Unit Owner's address last appearing on the books of the Council or supplied by such Unit Owner to the Council for the purpose of notice. Such notice shall specify the place, day and hour of the meeting, and, in the case of a special meeting, the purpose of meeting. If the said Unit Owner is a resident of Amberson Towers, it is sufficient compliance with this section to place the said notice in their mail box or deliver it to their Unit. 

### Section 5 {-}

The president, or in his absence, the Vice-President, shall preside at all such meetings. 

### Section 6 {-}

At every meeting of the Unit Owners, each Unit Owner present, in person or by proxy, and entitled to vote thereat, shall have the right to cast the number of shares set forth opposite his Unit number in Schedule A The vote of fifty-one (51) percent of the number of votes represented and entitled to vote at such meeting shall decide any question brought before such meeting, unless the question is one upon which, by express provision of statute or of the Declaration or of this Code of Regulations, a different vote is required, in which case, such express provisions shall govern and control.

### Section 7{-}

All proxies shall be in writing and shall be filed with the Secretary and by him entered of record in the minutes of the meeting. A Unit Owner may appoint only his or her spouse or another Unit Owner as his, her or its proxy. 

### Section 8 {-}

Either before or after any meeting, a Unit Owner may, in writing, waive notice of such meeting. Such waiver of notice in writing, signed by the person or persons entitled to such notice, whether before or after the time stated therein, shall be deemed equivalent to the giving of such notice. Except in the case of a special meeting, neither the business to be transacted at, nor the purpose of, the meeting need be specified in the waiver of notice of such meeting. 

### Section 9 {-}

Attendance of a Unit Owner, either in person or by proxy, at any meeting, shall constitute a waiver of notice of such meeting, except where a Unit Owner attend a meeting for the express purpose of objecting to the transaction of any business because the meeting was not lawfully called or convened. 

### Section 10 {-}

The number of Unit Owners having a majority of voting rights entitled to vote at any meeting, present in person or represented by proxy, shall constitute a quorum for the transaction of business. If, however, such majority shall not be present or represented at any meeting, the Unit Owners entitled to vote thereat, present in person or by proxy, shall have power to adjourn the meeting from time to time, without notice other than announcement of such meeting, until a majority as aforesaid shall be present or be represented. At such adjourned meeting, at which a quorum shall be present or represented, any business may be transacted which might have been transacted at the meeting as originally called. 

### Section 11 {-}

The order of business at all annual meetings of the Unit Owners shall, unless otherwise determined by action of the Unit Owners present or represented, be as follows:

(a) Roll call;  
(b) Proof of notice of meeting or waiver of notice;  
(c) Reading of minutes of preceding meeting;  
(d) Report of officers;  
(e) Reports of committees  
(f) Appointment of inspectors of election by the president or chair person;  
(g) Election of council;  
(h) Unfinished business;  
(i) New business;  

## ARTICLE V: Council {-}

### Section 1 {-}

The business and affairs of Amberson Towers shall be managed by a council composed of Five (5) persons, who shall be Unit Owners or officers or directors of a corporate Unit Owner, or partners of any partnership owning units, and Two (2) of whom shall be the President and Vice-President of Amberson Towers. 

### Section 2 {-}

Each Council member named in the Declaration shall hold office until the annual meeting of the Unit Owners in the year 1979 or until his successor shall have been elected and qualified, which shall first occur. 

### Section 3 {-}

At the annual meeting of the Unit Owners in the year 1979, the term of Office of Two (2) Council members elected shall be for three (3) years; and the term of office of Two (2) Council members shall be for Two (2) years; and the term of office of One (1) Council member elected shall be for One (1) year. The Council members receiving the largest number of votes shall serve the longest terms. At the expiration of the term of office of each respective Council member, his successor shall be elected to serve a term of Three (3) years. The Council member shall hold office until their successors have been elected and qualified. 

In all elections of Council members, each Unit Owner shall have the right, in person or by proxy, to multiply the number of votes to which he may be entitled by the number of directors to be elected and he may cast the whole number of said votes for one candidate or he May distribute them among any two or more candidates. 

### Section 4 {-}

Vacancies in the Council shall be filled by a majority of the remaining Council members and each person so elected shall be a Council member until his successor is elected by the Unit Owners, who may make such election at the next annual meeting of the Unit Owners or at any special meeting duly called for that purpose. 

### Section 5 {-}

Any one or more of the Council members may be removed with or without cause by vote of two-thirds of the Unit Owners entitled to vote at any duly held regular or special meeting of the Unit Owners, and a successor may be elected to fill the vacancy thus created. 

### Section 6 {-}

No person shall receive any compensation for acting as a Council member but may receive compensation for services rendered to or for Amberson Towers in any other capacity. 

### Section 7 {-}

The Council may exercise all such powers of Amberson Towers and may do all such acts and things, as are not by law or by this Code of Regulations directed or required to be exercised and done by the Unit Owners. 

### Section 8 {-}

The Council shall require that all officers and employees handling its funds shall furnish fidelity bonds in such amounts as the Council shall determine. The premium on such bonds shall be paid by Amberson Towers. 

### Section 9 {-}

Meetings of the Council may be held at such place within the County of Allegheny as a majority of the Council may from time to time designate or as may be designated in the notice calling the meeting. 

### Section 10 {-}

The first meeting of each new Council elected by the Unit Owners shall be held within thirty (30) days after such election upon at least five (5) days' written notice. 

### Section 11 {-}

Regular meetings of the Council may be held at such time or times and place as shall be determined by a majority of the Council. Notice of regular meetings of the Council shall be given to each Council member personally or by mail or by telegram, at least five (5) days prior to the day fixed for such meeting. 

### Section 12 {-}

Special meetings of the Council may be called by the President on not less than five (5) days' notice to each Council member either personally or by mail or by telegraph, which notice shall state the time, place and purposes of such meetings. Special meetings of the Council may also be called in like manner and upon like notice on the written request of at least three Council members. 

### Section 13 {-}

Either before or after any meeting of the Council any Council member may, in writing, waive notice of such meeting and such waiver shall be deemed equivalent to the giving of such notice. Attendance by a Council member at any meeting of the Council shall be a waiver by him of notice of the time and place thereof, unless said Council member has attended for the sole purpose of objecting to the meeting. If all the Council members are present at any meeting of the Council, except for the purpose of objecting to the transaction of any business for good and lawful cause, no notice shall be required and any business may be transacted at such meeting. 

### Section 14 {-}

At all meetings of the Council, a majority of the Council members in office shall be necessary to constitute a quorum for the transaction of business, and the acts of the majority of the Council members present at a meeting at which a quorum is present shall be the acts of the Council. If, at any meeting of the Council, there be less than a quorum present, the majority of those present may adjourn the meeting from time to time, At any such adjourned meeting, any business which might have been transacted at the meeting as originally called may be transacted without further notice. 

### Section 15 {-}

If all the Council members shall severally or collectively consent, in writing, duly filed with the Secretary to any action to be taken by Amberson Towers, such action shall be as valid as though it had been authorized at a meeting of the Council. 

### Section 16 {-}

The Council members, by resolution adopted by the majority of the entire Council, may at any time elect two (2) or more of their number as an executive committee which shall, in the intervals between meetings of the Council, exercise such powers and perform such duties as may from time to time be prescribed by the Council. Unless otherwise authorized by the Council, such committee shall act by unanimous vote of its members at a meeting or by a writing signed by all its members. Any act or thing done by such committee within the scope of the power delegated to it, shall be as effective for all purposes as the act or authorization of the Council. The committee shall keep regular minutes of its proceedings and shall report to the Council all actions taken by it. 

### Section 17 {-}

The Council shall have the following powers and duties in addition to those vested in it under the law, the Declaration and this Code of Regulations: 

(a) The maintenance, repair and replacement of the common elements; 

(b) The assessment and collection of funds from the Unit Owners for common expenses and the payment of such common expenses; 

(c) The promulgation, distribution and enforcement of rules governing the details of the use and operation of the property and the use of the common elements, subject to the right of the number of the unit owners which constitute 60 percent of the votes represented and entitled to vote at any regular or special meeting to change any such rules; 

(d) To appoint, employ and remove at any time any agent, or employee; and to prescribe the duties of and fix the compensation for any agent or employee. Nothing contained in this Code of Regulations shall be construed to prohibit the employment of any Unit Owners, Officers or Council Member in any capacity whatsoever; 

(e) To exercise for Amberson Towers all powers, duties, and authority vested in or delegated to it which it may lawfully exercise, in carrying out or in furtherance of its purposes or any of them; 

(f) To submit at each annual meeting of the Unit Owners a statement of the operations of Amberson Towers during the preceding year, together with a report of its general financial condition. Copies of such annual financial reports shall be sent to each Unit Owners within sixty (60) days following the close of the preceding fiscal year, along with a copy to the Mortgagee of any Unit who has requested the same in writing; the said mortgagees can also examine the books and records of the condominium; 

(g) To make or cause to be made a proposed budget for the ensuing year, a copy of which shall be mailed to each Unit Owner at least ten (10) days prior to the annual meeting. 

(h) To elect all officers and to fill all vacancies which may occur. 

## ARTICLE VI: Officers {-}

### Section 1 {-}

The officers of Amberson Towers shall be a president, a vice-president, a secretary and a treasurer, and such other officers as the Council may create by resolution from time to time. Any officer may be removed by a majority of the entire Council at any time. All of said officers shall be elected by the Council and each such officer shall hold office until his successor is elected and qualified. No person may be the president or vice-president who shall not be a Unit Owner or an Officer or director of a corporate Unit Owner, or a partner of any partnership owning a unit. 

### Section 2 {-}

The election of officers shall take place at the first meeting of the Council following each annual meeting of the Unit Owners. 

### Section 3 {-}

The president and vice-president of Council shall be the president and vice-president of Amberson Towers. 

### Section 4 {-}

The president shall be the chief executive officer of Amberson Towers. He shall preside at all meetings of the Unit Owners and of the Council. He shall have general and active management of the business of Amberson Towers. 

### Section 5 {-}

The vice-president shall, in the absence or disability of the president, perform the duties and exercise the powers of the president. He shall also perform such other duties as shall from time to time be delegated to him by the Council. 

### Section 6 {-}

The secretary shall keep the minutes of all meetings of the Unit Owners; he or she shall have charge of such of the books and papers as the Council may direct, all of which shall, at reasonable times and for reasonable purposes, be open to the examination of any Unit Owner, Officer or Council member, upon application at the office of Amberson Towers during business hours. 

### Section 7 {-}

The treasurer shall have custody of Amberson Towers funds and securities and shall cause full and accurate accounts of receipts and disbursements to be kept in books belonging to Amberson Towers. He shall deposit all monies and other valuable effects in the name, and to the credit of Amberson Towers in such depositories as may from time time be designated by the Council. 

### Section 8 {-}

An assistant secretary, if appointed, shall in the absence or disability of the secretary, perform the duties and exercise the powers of the secretary and such other duties as shall be delegated to him by the Council. 

### Section 9 {-}

As assistant treasurer, if appointed, shall, in the absence or disability of the treasurer, perform the duties and exercise the powers of the treasurer. 

### Section 10 {-}

No person shall receive any compensation for acting as an officer of Amberson Towers but may receive compensation for services rendered to or for Amberson Towers in any other capacity.

## ARTICLE VII: Payment of Common Expenses and Other Expenses by Unit Owners {-}

### Section 1 {-}

As provided in Article V, Section 17, the Council shall determine all matters relating to maintenance, repair and replacement of the common elements and also all matters relating to the common expenses. 

### Section 2 {-}

The Council shall pro-rate all costs involved in Section 1 above, among all the Unit Owners in proportion to their ownership in the common elements, provided, however, that if any cost is occasioned by the negligence of any unit owner or owners, said costs shall be borne by said unit owner or owners. 

### Section 3 {-}

The total amount of the charges required for each calendar year shall be estimated by the Council at least one (1) month prior to the beginning of each calendar year. Such estimate may include an amount for unanticipated or under-estimated costs, charges and expenses and deficits incurred in any prior year or years, and may further include amounts to be accumulated in any reserve funds for expenditures which may be required in future years for other than ordinary current maintenance, repairs, costs and expenses. The first such charge may be estimated and made for less than a full year, and in such event the Maintenance Charge for such period shall be payable in equal monthly installments for the remainder of such calendar year, beginning on the first day of the month immediately following the determination of such estimate by the Council. Thereafter, each annual Maintenance Charge shall be payable in twelve (12) equal monthly installments beginning on the first day of January of each calendar year. 

The annual budget shall be sent to Unit Owners at least ten (10) days prior to the annual meeting, at which time the budget shall be approved in the same manner as other business brought before the meeting. After the annual budget has been approved by the required vote, the Council shall cause a statement to be sent to each Unit Owner; which statement shall reflect the total amount of the annual maintenance budget thus approved, the common element percentage obligation therefor attaching to each respective unit and the corresponding monthly payments to be made by each Unit Owner. Each Unit Owner shall then be required to make his respective Monthly Maintenance Payment to the Council or its designee without further billing or request therefor. Any charge assessed against a unit may be enforced by suit by the Council acting on behalf of the unit owners in an action in assumptive; provided, that each suit when files shall refer to the Unit Property Act, Act of July 3, 1963, P.L. 196, and to the unit against which the assessment is made and the owner thereof and shall be indexed by the probationary as lis pendens. Any judgment against a unit and its owners shall be enforceable in the same manner as is otherwise provided by law.

Until the Council shall otherwise determine, the monthly charges to be paid by each Unit Owner shall be in accordance with the budget attached. 

### Section 4 {-}

In the event that the Council decides that additional monies are required in addition to those set forth in the annual budget, the Council shall give the Unit Owners at least Thirty (30) days written notice of the total monies required and allocate amounts among the Unit Owners together with time for payment of said proportionate amounts which may be at one time or in installments, as the Council decides, provided, however, that if Unit Owners representing forty (40%) percent of the votes of Amberson Towers object in writing to said additional assessments within fifteen (15) days after mailing of such notice, the Council shall call a special meeting of the Unit Owners for the purpose of obtaining approval of said assessments, at which meeting the assessments of the Council must receive the same affirmative vote as in the case of the annual budget. 

### Section 5 {-}

Any surplus funds remaining at the end of the calendar year may, at the discretion of and at the time determined by the Council, be refunded in whole or in part to the then Unit Owners proportionately according to the common element percentages attaching to each unit, or may be applied in the said proportion as a result to future Maintenance Charges to become payable by each Unit Owner for each dwelling unit or may be deposited to any reserve fund established by Council. In the event that any refunds or credits against future Maintenance Charges are to be made or given, the amount thereof to which any such Unit Owner shall be entitled may be applied toward the payment of any indebtedness of such Unit Owner to Council. 

### Section 6 {-}

The Council shall maintain fire and other hazard and liability insurance on the entire property, and take charge of disbursement of fire and other hazard insurance and other proceeds for repair or reconstruction of any portion of the property, and arranging for the management of the property pursuant to an agreement containing provisions relating to the duties, obligations, removal and compensation of the management agent. 

### Section 7 {-}

From the funds appropriated under and pursuant to the Annual Budget and paid to the Council by way of Monthly Maintenance Payments, the Council shall acquire and pay for: 

(a) A policy or policies of fire and other hazard insurance for the full insurable value (replacement cost) of the building and improvements in the project (unless paid for by mortgage from funds impounded for that purpose). These policies shall be reviewed once a year and increased as necessary to provide maximum coverage. Such insurance shall be obtained in the name of the Council as Trustee for all of the owners and their mortgagees, as their interest appears. The provisions hereof are not to be construed as diminishing the right of such owner to insure his particular unit for the owner's individual benefit; 

(b) A policy or policies of insurance insuring the Council and all of the Unit Owners against any liability to the public or to the Unit Owners, their invitees, guests, and tenants, incident to the ownership and use of the common elements and the units; the liability under such policies shall be not less than One Million ($1,000,000) Dollars for any one accident, and One Hundred Thousand ($100,000) Dollars for property damage, and such policy limits shall be reviewed at least every three (3) years by the Council and may be increased in its discretion. Said policy to cover acts of Council and officers. 

(c) A policy of Workman's Compensation Insurance to the extent necessary to comply with applicable laws. 

### Section 8 {-}

The holder of a first mortgage or any unit shall be entitled to give written notice of the existence of its mortgage to the Council and shall include in such notice an address to which all notices and correspondence may be sent. If the holder of a first mortgage has given such notice to Council, it shall be entitled to written notice from the Council of any default by its mortgagor in the performance of such mortgagor's obligations under the condominium regime which is not cured within thirty (30) days. 

## ARTICLE VIII: Sale or Lease by Unit Owner {-}

Any owner who wishes to sell, lease, or rent his unit shall, at least thirty (30) days prior to accepting any offer to sell, lease or rent, give to Council written notice of the terms of such offer, which notice shall specify the name and address of the offeror. If, within said thirty (30) day period, time being of the essence, Council or its nominee submits to the owner an identical or more favorable offer to sell, lease, or rent, the selling owner must accept the offer of said Council in preference to the original offer described in the notice. In the event Council fails to submit in writing to the selling owner an identical or more favorable offer within thirty (30) days of receipt of notice of the selling owner's offer, time being of the essence, then the selling owner may sell his apartment to his original offeror. In any event Council, shall have sole discretion in this matter and no vote or approval of the Unit Owners is required. Any holder of a mortgage which comes into possession of a unit pursuant to the remedies provided in the mortgage or any purchaser at a sheriff sale of the unit or any mortgagee, or its designee, who accepts a deed for the unit in lieu of foreclosure shall be exempt from the provisions of this Section.

## ARTICLE IX: Miscellaneous {-}

### Section 1 {-}

All bills payable, notes, checks or other negotiable instruments and all contracts of Amberson Towers shall be made in the name of Amberson Towers, a condominium, and shall be executed by the President or Vice-President and by the Secretary or Treasurer, unless otherwise authorized by the Council. 

### Section 2 {-}

The fiscal year of Amberson Towers shall begin on the first day of January and end on the 31st day of December of every year except that the first fiscal year shall begin as of the recording of the deed of the first unit. 

### Section 3 {-}

No contract or other transaction between Amberson Towers and any other corporation, firm or individual, and no act of the Council members, officers or Unit Owners shall, in any way, be affected or invalidated by the fact that any of its Unit Owners, Council members or Officers is pecuniarily or otherwise interested as an owner, Council member, officer or otherwise in such corporation or firm; provided, that such fact shall be disclosed to the Council; and any Council member who is also a shareholder, director, employee or officer of such other corporation or a member, employee or officer of such other corporation or a member, employee or owner of such other firm, or who is so interested may be counted in determining the existence of a quorum at any meeting of Council which shall authorize such contract or transaction, and may vote thereat to authorize such contract or transaction with life effect as if her were not such shareholder, director, officer, member, employee or owner of such other corporation or firm, or were not so interested. 

## ARTICLE X: Maintenance of Patios, If Any {-}

While all adjacent and connecting terraces or patios at ground level and above connected to individual apartments are common elements, each unit Owner has an exclusive easement for the use and enjoyment of the terrace or patio adjacent and connecting with his individual apartment. Accordingly, the costs of maintenance thereof shall rest with and be borne by the Unit Owner of the apartment to which said terrace or patio is connected, if any. 

## ARTICLE XI: Modification and Amendment {-}

Notwithstanding anything in this Code of Regulations to the contrary, this Code of Regulations may be altered, revised or modified upon the written consent of the numbered Unit Owners representing Sixty (60%) percent of the votes of Amberson Towers. Any such revision, alteration, or modification shall be recorded in the Recorder's Office of Allegheny County, Pennsylvania, and shall become effective as of the date of such recording. 

Any modification which affects a particular Unit only shall have the approval of that particular unit holder and the mortgagee of the same. 

## ARTICLE XII: Construction of Provisions {-}

The provisions of this Code of Regulations shall be liberally construed to effectuate its purpose of creating a uniform plan for the development and operation of a condominium apartment building. Failure to enforce any provision thereof will not constitute a waiver of the right to enforce said provision or any other provision hereof. 

## ARTICLE XIII: Conflicts Between Declaration and Code of Regulations {-}

In the event of any conflict or inconsistency between this Code of Regulations and the Declaration, the Declaration shall govern. 

## ARTICLE XIV: Severability of Provisions {-}

The provisions hereof shall be deemed independent and severable, and the invalidity or partial invalidity of any part shall not affect the enforceability of any other provision hereof. 

## ARTICLE XV: Exculpability of Council and Officers {-}

Neither the Council as a body nor any member thereof nor any officer shall be personally liable to any Unit Owner in any respect for any action or lack of action arising out of the execution of this office. Each Unit Owner shall be bound by the good faith actions of the Council and Officers of Amberson Towers in the execution of the duties of said Councilmen and Officers. Unless acting in bad faith, no Councilman or Officer shall be liable to any Unit Owner or other person for misfeasance or malfeasance in office. 

## ARTICLE XVI {-}

The Council shall from time to time issue rulings, regulations and conditions which shall be binding upon all Apartment Unit Owners which rulings, regulations and conditions shall be in the Council's sole judgment for the general well-being, safety, care and cleanliness of the building and shall include but shall not be limited to the following. 

1. No animals, birds or pets of any kind shall be brought or kept in or about the apartment unit or the building of which it is a part. 
2. All Unit Owners shall provide white curtain liners or white glass curtains as are presently used in the building. Washers and, dryers are not permitted in the units. 
3. Each apartment unit shall be carpeted in an amount equal to 80% of the floor space in every room, corridor, foyer and/or vestibule with the exception of the kitchen and bathrooms.
4. Each Unit Owner shall carry an apartment owner's comprehensive insurance policy covering the inside of his apartment for contents and liability insurance therein. 

IN WITNESS WHEREOF, the undersigned adopt this within Code of Regulations this 14th day of February, 1978. 

AMBERSON TOWERS,  
a Condominium

BY: Harry S. Kalson  
BY: Paul Kossis  
BY: George Dimeling  
BY: James Kossis  
BY: Al Raizman  

## Schedule A {-}

| APT. UNIT NO.  | PERCENTAGE | 
| :------------- | :--------- |
| 100            | 0.6747%    |
| 101            | 0.3767%    |
| 102            | 0.3767%    |
| 103            | 0.6747%    |
| 104            | 0.4675%    |
| 105            | 0.4548%    |
| 106            | 0.4633%    |
| 107            | 0.4548%    |
| 109            | 0.6376%    |
| 111            | 0.4570%    |
| 112            | 0.6551%    |
| 113            | 0.6147%    |
| 114            | 0.4675%    |
| 115            | 0.3597%    |
| 116            | 0.4675%    |
| 117            | 0.3442%    |
| 118+120        | 1.0956%    |
| 119            | 0.6747%    |
| 121            | 0.3767%    |
| 200            | 0.6747%    |
| 201            | 0.3767%    |
| 202            | 0.3767%    |
| 203            | 0.6747%    |
| 204            | 0.4675%    |
| 205            | 0.4548%    |
| 206            | 0.4633%    |
| 207            | 0.4548%    |
| 209            | 0.6376%    |
| 210            | 0.4463%    |
| 211            | 0.4570%    |
| 212            | 0.8028%    |
| 213            | 0.6147%    |
| 214            | 0.4675%    |
| 215            | 0.4505%    |
| 216            | 0.4675%    |
| 217            | 0.4548%    |
| 218            | 0.6747%    |
| 219            | 0.6747%    |
| 220            | 0.3767%    |
| 221            | 0.3767%    |
| 300            | 0.6747%    |
| 301            | 0.3767%    |
| 302            | 0.3767%    |
| 303            | 0.6747%    |
| 304            | 0.4675%    |
| 305            | 0.4548%    |
| 306            | 0.4633%    |
| 307            | 0.4548%    |
| 308            | 0.4740%    |
| 309            | 0.6376%    |
| 310            | 0.4463%    |
| 311            | 0.4570%    |
| 312            | 0.8028%    |
| 313            | 0.6147%    |
| 314            | 0.4675%    |
| 315            | 0.4505%    |
| 316            | 0.4675%    |
| 317            | 0.4548%    |
| 318            | 0.6747%    |
| 319            | 0.6747%    |
| 320            | 0.3767%    |
| 321            | 0.3767%    |
| 400            | 0.6747%    |
| 401            | 0.3767%    |
| 402            | 0.3767%    |
| 403            | 0.6747%    |
| 404            | 0.4675%    |
| 405            | 0.4548%    |
| 406            | 0.4633%    |
| 407            | 0.4548%    |
| 408            | 0.4740%    |
| 409            | 0.6376%    |
| 410            | 0.4463%    |
| 411            | 0.4570%    |
| 412            | 0.8028%    |
| 413            | 0.6147%    |
| 414            | 0.4675%    |
| 415            | 0.4505%    |
| 416            | 0.4675%    |
| 417            | 0.4548%    |
| 418            | 0.6747%    |
| 419            | 0.6747%    |
| 420            | 0.3767%    |
| 421            | 0.3767%    |
| 500            | 0.6747%    |
| 501            | 0.3767%    |
| 502            | 0.3767%    |
| 503            | 0.6747%    |
| 504            | 0.4675%    |
| 505            | 0.4548%    |
| 506            | 0.4633%    |
| 507            | 0.4548%    |
| 508            | 0.4740%    |
| 509            | 0.6376%    |
| 510            | 0.4463%    |
| 511            | 0.4570%    |
| 512            | 0.8028%    |
| 513            | 0.6147%    |
| 514            | 0.4675%    |
| 515            | 0.4505%    |
| 516            | 0.4675%    |
| 517            | 0.4548%    |
| 518            | 0.6747%    |
| 519            | 0.6747%    |
| 520            | 0.3767%    |
| 521            | 0.3767%    |
| 600            | 0.6747%    |
| 601            | 0.3767%    |
| 602            | 0.3767%    |
| 603            | 0.6747%    |
| 604            | 0.4675%    |
| 605            | 0.4548%    |
| 606            | 0.4633%    |
| 607            | 0.4548%    |
| 608            | 0.4740%    |
| 609            | 0.6376%    |
| 610            | 0.4463%    |
| 611            | 0.4570%    |
| 612            | 0.8028%    |
| 613            | 0.6147%    |
| 614            | 0.4675%    |
| 615            | 0.4505%    |
| 616            | 0.4675%    |
| 617            | 0.4548%    |
| 618            | 0.6747%    |
| 619            | 0.6747%    |
| 620            | 0.3767%    |
| 621            | 0.3767%    |
| 700            | 0.6747%    |
| 701            | 0.3767%    |
| 702            | 0.3767%    |
| 703            | 0.6747%    |
| 704            | 0.4675%    |
| 705            | 0.4547%    |
| 706            | 0.4633%    |
| 707            | 0.4548%    |
| 708            | 0.4740%    |
| 709            | 0.6376%    |
| 710            | 0.4463%    |
| 711            | 0.4570%    |
| 712            | 0.8028%    |
| 713            | 0.6147%    |
| 714            | 0.4675%    |
| 715            | 0.4505%    |
| 716            | 0.4675%    |
| 717            | 0.4548%    |
| 718            | 0.6747%    |
| 719            | 0.6747%    |
| 720            | 0.3767%    |
| 721            | 0.3767%    |
| 800            | 0.6747%    |
| 801            | 0.3767%    |
| 802            | 0.3767%    |
| 803            | 0.6747%    |
| 804            | 0.4675%    |
| 805            | 0.4548%    |
| 806            | 0.4633%    |
| 807            | 0.4547%    |
| 808            | 0.4740%    |
| 809            | 0.6376%    |
| 810            | 0.4463%    |
| 811            | 0.4570%    |
| 812            | 0.8028%    |
| 813            | 0.6147%    |
| 814            | 0.4675%    |
| 815            | 0.4505%    |
| 816            | 0.4675%    |
| 817            | 0.4548%    |
| 818            | 0.6747%    |
| 819            | 0.6747%    |
| 820            | 0.3767%    |
| 821            | 0.3767%    |
| 900            | 0.6747%    |
| 901            | 0.3767%    |
| 902+903        | 1.0918%    |
| 904            | 0.4675%    |
| 905            | 0.4548%    |
| 906            | 0.4633%    |
| 907            | 0.4548%    |
| 908            | 0.4740%    |
| 909            | 0.6376%    |
| 910            | 0.4463%    |
| 911            | 0.4570%    |
| 912            | 0.8028%    |
| 913            | 0.6147%    |
| 914            | 0.4675%    |
| 915            | 0.4505%    |
| 916            | 0.4675%    |
| 917            | 0.4548%    |
| 918            | 0.6747%    |
| 919+921        | 0.8410%    |
| 920            | 0.3767%    |